# These are supported funding model platforms

github: [your-username]
patreon: # Replace with Patreon username
open_collective: dual-ai-tools
ko_fi: # Replace with Ko-fi username
tidelift: # npm/dual-ai-tools
community_bridge: # Replace with Community Bridge project-name
liberapay: # Replace with Liberapay username
issuehunt: # Replace with IssueHunt username
otechie: # Replace with Otechie username
lfx_crowdfunding: # Replace with LFX Crowdfunding project-name
custom: ['https://your-domain.com/pricing', 'https://your-domain.com/sponsor']